version: '3'

services:
  spring-boot:
    container_name: spring-boot
    image: openjdk:17-jdk-slim
    ports:
      - "8080:8080"
    volumes:
      - ./target/kotlinspring-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: ["java", "-jar", "/app/app.jar"]
